# Generated by Django 4.2.10 on 2024-02-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Menu", new_name="MenuItem",),
    ]
